#!/usr/bin/env bash

set -eu

CONFIG_PATH=$GENKA_ROOT/config
API_URL=$( cat $CONFIG_PATH/api.url )

create () {
  http post $API_URL/$1s/ name=$2 | jq .
}

case $1 in
  project | stage | member )
    if [ -n "$2" ]
    then
      create $1 $2
    else
      echo "genka create [project|stage|member] name"
      exit 2
    fi
    ;;
  * )
    echo "genka create [project|stage|member] name"
    exit 1
    ;;
esac
