#!/usr/bin/env bash

set -eu

CONFIG_PATH=$GENKA_ROOT/config
API_URL=$( cat $CONFIG_PATH/api.url )
RESOURCES_PATH=$GENKA_ROOT/resources

load_resources() {

  mkdir $RESOURCES_PATH/$1
  RESOURCES=$(http get $API_URL/$1)
  COUNT=$(echo $RESOURCES | jq .[].name | wc -l)

  for i in `seq 0 $(expr $COUNT - 1)`
  do
    ID=$(echo $RESOURCES | jq -r .[$i].id)
    NAME=$(echo $RESOURCES | jq -r .[$i].name)

    echo $ID > $RESOURCES_PATH/$1/$NAME
  done

}

rm -rf  $RESOURCES_PATH/*

load_resources projects
load_resources stages
load_resources members
