#!/usr/bin/env bash

set -eu

CONFIG_PATH=$GENKA_ROOT/config
API_URL=$( cat $CONFIG_PATH/api.url )
RESOURCES_PATH=$GENKA_ROOT/resources

create () {
  RESULT=$(http post $API_URL/$1s/ name=$2 | jq .)
  if $(echo $RESULT | jq 'has("id")')
  then
    ID=$(echo $RESULT | jq -r .id)
    NAME=$(echo $RESULT | jq -r .name)
    echo $ID > $RESOURCES_PATH/$1s/$NAME
    echo created: $RESULT
  else
    echo error: $RESULT
  fi
}

case $1 in
  project | stage | member )
    if [ -n "$2" ]
    then
      create $1 $2
    else
      echo "genka create [project|stage|member] name"
      exit 2
    fi
    ;;
  * )
    echo "genka create [project|stage|member] name"
    exit 1
    ;;
esac
